### ISSUE TITLE
References to the "packaging operator"... should we?

### ISSUE THREAD

**Issue by OmarCordovani** [patricktoohey/packml-hmi#10]
I feel like the document refers too many times to the "packaging operator", while then we often promote PackML also for other discrete applications. For example, at page 8, I would rather write "In the context of Production Machines operations", or "production lines", but not "in the context of the packaging operator".

**Comment by patricktoohey** [comment]
Updated throughout. Will need to review final draft to ensure additional examples have not been reintroduced.
