### ISSUE TITLE
Overall consistency with conventions for uppercase words

### ISSUE THREAD

**Issue by OmarCordovani** [patricktoohey/packml-hmi#11]
-packml states... should we keep them all written in uppercase?
-"PackML Stack Light standard" sometimes the words have uppercase first letters, sometimes not...

**Comment by patricktoohey** [comment]
For readability purposes, I would avoid presenting the states in all uppercase. While it would aid the readers ability to scan the document to find references to states, it is generally more difficult to read text that is fully capitalized.

**Comment by patricktoohey** [comment]
Capitalize the First letter whenever a state is referenced.

**Comment by patricktoohey** [comment]
Stacklight one word, lowercase colors, Lamp OK
