### ISSUE TITLE
Clearer statement about what we propose as a standard

### ISSUE THREAD

**Issue by OmarCordovani** [patricktoohey/packml-hmi#13]
As we have already discussed many times, the document will provide guidelines and best practices recommendations. Anyway I think that we should state more clearly what are the main points of the standard. The content with many examples and explanation is very exhaustive but not "straight to the point". Many requests come to my desk about what is "mandatory to do to be OMAC compliant" and what is not. I feel that with such document those questions will increase.

**Comment by patricktoohey** [comment]
We can include language in section 2 that will summarize the content of the document (i.e., standards plus guidance) and specifically identify those sections that constitute the standard. Section 4 presents a brief summary in section 4.1 followed by the "standard" in section 4.2. We can include a summary in section 2 to mark all "standard" sections and note that readers only interested in the standards can skip the remaining guidance content.

**Comment by patricktoohey** [comment]
Adding section 2.3 to summarize the document structure and point the reader to the content most important to their goals.
