### ISSUE TITLE
Typing errors corrections, attempt to improve readability - see attached pdf

### ISSUE THREAD

**Issue by OmarCordovani** [patricktoohey/packml-hmi#9]
[PackML HMI Implementation Guidance Draft 01A_OmarCordovani.pdf](https://github.com/patricktoohey/packml-hmi/files/2812781/PackML.HMI.Implementation.Guidance.Draft.01A_OmarCordovani.pdf)

-Some paragraphs look pretty heavy to read (especially for non native English speakers :) ), sometimes the concept is brought too many times back and forth. I tried to simplify some of them.
-Some general typing corrections here and there (commas, misspelling, words repetitions...)

**Comment by OmarCordovani** [comment]
-Some paragraphs look pretty heavy to read (especially for non native English speakers :) ), sometimes the concept is brought too many times back and forth. I tried to simplify some of them. 
-Some general typing corrections here and there (commas, misspelling, words repetitions...)

**Comment by patricktoohey** [comment]
Moved typos to #14

**Comment by patricktoohey** [comment]
- [ ] Remove 'and' from subtitle
- [ ] Paragraph [0002] join sentences with a 'which'
- [ ] Paragraph [0004] replace semicolon with a colon
- [ ] Paragraph [0004] replace 'their' with 'the'
- [ ] Paragraph [0005] replace 'goals' with 'needs'
- [ ] Paragraph [0007] replace 'part' with 'side'
- [ ] Paragraph [0007] fix redundant 'our'
- [ ] Paragraph [0007] optimize designer satisfaction sentence
- [ ] Paragraph [0009] rewrite
- [ ] Paragraph [0010] rewrite
- [ ] Paragraph [0017] pluralize 'achieve'
- [ ] Paragraph [0019] remove 'is not flawed'
- [ ] Paragraph [0021] update to 'level 3 SA needs'
- [ ] Paragraph [0022] remove 'additional' and replace verb with 'are'
- [ ] Paragraph [0023] update to read 'critical indicator?'
- [ ] Paragraph [0023] update to read 'high level of uncertainty?'
- [ ] Paragraph [0026] replace 'Fortunately' to eliminate redundancy
- [ ] Paragraph [0027] replace 'that are' with a comma
- [ ] Paragraph [0028] replace 'select' with 'selected'
- [ ] Paragraph [0030] Stopped and Aborted
- [ ] Paragraph [0031] end sentence prior to 'however' (i.e., replace comma with period)
- [ ] Paragraph [0033] remove 'where the consistency is maintained'
- [ ] Paragraph [0040] add 'for example'
- [ ] Paragraph [0042] update to bulleted list

**Comment by patricktoohey** [comment]
Completed review. Updates will be included in next draft
